
name: Workflow 2 - Multi Platform

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create and print file
        run: |
          echo "Hello from Ubuntu" > info.txt
          cat info.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: systeminfo
      - name: Create and print file
        run: |
          echo Hello from Windows > info.txt
          type info.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create and print file
        run: |
          echo "Hello from macOS" > info.txt
          cat info.txt
